if(NOT DEFINED SE_EXE OR NOT DEFINED SE_ROOT OR NOT DEFINED SE_WORK)
  message(FATAL_ERROR "SE_EXE, SE_ROOT and SE_WORK are required")
endif()
file(REMOVE_RECURSE "${SE_WORK}")
file(MAKE_DIRECTORY "${SE_WORK}")
file(COPY "${SE_ROOT}/examples/expansion-content.se" DESTINATION "${SE_WORK}")
execute_process(COMMAND "${SE_EXE}" build "${SE_WORK}/expansion-content.se"
  WORKING_DIRECTORY "${SE_WORK}" RESULT_VARIABLE built OUTPUT_VARIABLE build_out ERROR_VARIABLE build_err)
if(NOT built EQUAL 0)
  message(FATAL_ERROR "Native expansion build failed:\n${build_out}\n${build_err}")
endif()
execute_process(COMMAND "${SE_WORK}/expansion-content"
  WORKING_DIRECTORY "${SE_WORK}" RESULT_VARIABLE ran OUTPUT_VARIABLE out ERROR_VARIABLE err)
if(NOT ran EQUAL 0 OR NOT out MATCHES "SE content expansion OK")
  message(FATAL_ERROR "Native expansion run failed:\n${out}\n${err}")
endif()
